import {game} from "../sgc/sgc.js";

game.preloadImage("water.png");
game.preloadImage("slider.png");
game.preloadImage("start.png");
game.preloadImage("finish.png");
game.preloadImage("door.png");
game.preloadImage("wall.png");
game.preloadImage("ann.png", 48, 48);
game.preloadImage("bat.png", 48, 48);
game.preloadImage("spider.png", 48, 48);
game.preloadImage("Bone_1.png");
game.preloadImage("Bone_2.png");
game.preloadImage("Bone_3.png");
game.preloadImage("Bone_4.png");
game.preloadImage("Cemetery.png");
game.preloadImage("Crate.png");
game.preloadImage("Tile_5.png");
game.preloadImage("Tile_6.png");
game.preloadImage("Tile_7.png");
game.preloadImage("Tile_8.png");
game.preloadImage("Tile_9.png");
game.preloadImage("Tile_10.png");
game.preloadImage("Tile_11.png");
game.preloadImage("tileBottomCenter.png");
game.preloadImage("tileBottomRight.png");
game.preloadImage("tileFloatCenter.png");
game.preloadImage("tileFloatRight.png");
game.preloadImage("tileFloatLeft.png");
game.preloadImage("tileTopCenter.png");
game.preloadImage("tileTopLeft.png");
game.preloadImage("tileTopRight.png");
game.preloadImage("TombStone1.png");