import {game} from "../sgc/sgc.js";

game.preloadImage("water.png");
game.preloadImage("slider.png");
game.preloadImage("start.png");
game.preloadImage("finish.png");
game.preloadImage("door.png");
game.preloadImage("wall.png");
game.preloadImage("ann.png", 48, 48);
game.preloadImage("bat.png", 48, 48);
game.preloadImage("spider.png", 48, 48);
game.preloadImage("Bone1.png");
game.preloadImage("Bone2.png");
game.preloadImage("Bone3.png");
game.preloadImage("Bone4.png");
game.preloadImage("Cemetery.png");
game.preloadImage("Crate.png");
game.preloadImage("Tile5.png");
game.preloadImage("Tile7.png");
game.preloadImage("Tile8.png");
game.preloadImage("Tile10.png");
game.preloadImage("Tile11.png");
game.preloadImage("tileBottomCenter.png");
game.preloadImage("tileBottomRight.png");
game.preloadImage("tileFloatCenter.png");
game.preloadImage("tileFloatRight.png");
game.preloadImage("tileFloatLeft.png");
game.preloadImage("tileTopCenter.png");
game.preloadImage("tileTopLeft.png");
game.preloadImage("tileTopRight.png");
game.preloadImage("TombStone1.png");